### ISSUE TITLE
Issue, error on   var taxPercent = EuropeanVat.Countries.ContainsKey(user.IPAddressCountry) ? EuropeanVat.Countries[user.IPAddressCountry] : 0;

### ISSUE THREAD

**Issue by nin9creative** [pedropaf/saas-ecom-my-notes-sample#1]
Trying to run this sample and getting a YSOD.

Server Error in '/' Application.

Value cannot be null.
Parameter name: key

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: key

Source Error: 

Line 190:                {
Line 191:                    // Create Stripe user
Line 192:                    var taxPercent = EuropeanVat.Countries.ContainsKey(user.IPAddressCountry) ? 
Line 193:                        EuropeanVat.Countries[user.IPAddressCountry] : 0;
Line 194:                    await SubscriptionsFacade.SubscribeUserAsync(user, model.SubscriptionPlan, taxPercent: taxPercent);

**Comment by pedropaf** [comment]
I just pushed a fix for that error, it's happening because running locally user.IPAddressCountry is null. I'm checking for null now. Please let me know if that works for you. Thanks!

**Comment by nin9creative** [comment]
Cool thanks.  I did the same to get around the issue :)    I must say this framework is awesome.  Saving me a ton of time in working on a SaaS project.

With the Notes demo, are there any admin screens?  I thought I had seen some admin screens in screenshots on the main project site.

Thanks!

**Comment by pedropaf** [comment]
I removed that functionality when I created the NuGet packages as it didn't really provide any extra information that what you get from Stripe. You can also consider integrating Intercom to get useful data about your customers.

When you have your SAAS live please let me know so I can feature you on the new website for SAAS Ecom.
